"""add language to posts

Revision ID: 60566c34ce03
Revises: c5638ceedd1f
Create Date: 2023-07-26 15:04:08.815544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60566c34ce03'
down_revision = 'c5638ceedd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
